# Generated by Django 6.0.3 on 2026-04-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
